### ISSUE TITLE
Outdated copy of FontAwesome included

### ISSUE THREAD

**Issue by esafak** [spiroid/pelican-hpstr#5] opened 2014-08-01 09:37 UTC
The included version, 3.1, is from last year. The current version is 4.1, and includes useful new social icons, such as Stack Exchange. It would be useful to users to explain in the documentation that they can add social icons for any service that's included in [this list](http://fortawesome.github.io/Font-Awesome/icons/) by simply writing the part that comes after the `fa-` prefix.

**Comment by spiroid** [comment] 2014-08-05 21:58
The version of FontAwesome included is 4.1.0.
You can check this by reading the header of the [font awesome css file](https://github.com/spiroid/pelican-hpstr/blob/master/static/css/font-awesome.min.css)

<pre>
 *  Font Awesome 4.1.0 by @davegandy - http://fontawesome.io - @fontawesome
</pre>

I'll add a link to font awesome documentation from the readme file to make it clear to users how to insert icons.

**Comment by esafak** [comment] 2014-08-05 22:28
It's the [actual fonts](https://github.com/spiroid/pelican-hpstr/blob/master/static/fonts/fontawesome-webfont.ttf) that are outdated, not the CSS. You might want to merge or at least look at my fork, which fixes this problem, and has some other features too.

**Comment by spiroid** [comment] 2014-08-07 10:23
@esafak, can you please check that the issue is fixed by the commits in the referenced pull request ?

thx

**Comment by esafak** [comment] 2014-08-07 18:13
I checked the OTF and TTF. Looks good. You can close this upon merging.

**Comment by spiroid** [comment] 2014-08-07 18:22
ok thx for the feedback

**Closed as completed** 2014-08-08 07:33 UTC
Labels: bug
